import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/AuthContext';
import { ProductProvider } from '@/context/ProductContext';
import ProtectedRoute from '@/route/ProtectedRoute';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Foot Style",
  description: "Generated by Puvanakopis",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background font-display text-foreground antialiased`}>
        <AuthProvider>
          <ProductProvider>
            <ProtectedRoute>
              {children}
            </ProtectedRoute>
          </ProductProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
